apiVersion: apps/v1
kind: Deployment
metadata:
  name: reedis-deployment
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: redis
        ports:
        - containerPort: 6379